### PR TITLE
Earthdawn Support for 50 and 4th ed

### PR DESCRIPTION
**Pull request by criticalfault**
Here is  pull for adding the steps of the original Earthdawn up to 50, As well 4th editions steps up to 40. Added new command "ed4" to use with it.
This is in reference to #189

### CODE REVIEW

**Comment by Humblemonk** [comment]
Awesome! Thanks for the commit. I will look to getting this merged this weekend.

**Comment by criticalfault** [comment]
Thanks man! I am excited to be able to help the Earthdawn Community. We play in our server and it will save us a bunch of time to have it added. Amazing product. Glad to be able to give something back to it!

**Comment by criticalfault** [comment]
I was thinking, we may want to make it ed4th or something for the command. I'm not coming up with anything really good for switching between the two. ed410 just feels... odd, you know? 

Anyway, let me know if you think of anything with it!

**Comment by Humblemonk** [comment]
Hmm what if do something like "ed4e" for specifying its 4th edition?

**Comment by criticalfault** [comment]
That sounds perfect. I hope it will be enough to make it make sense and not be confusing.

**Comment by criticalfault** [comment]
I added 2 new fixes if you would review when you get a chance. Make sure it works the way i think it does. This is my first time in ruby, but it seem easy enough to make these changes.

**Comment by Humblemonk** [comment]
I think we are good. Going to merge it and run some tests but I think we are good to go. Thanks again for the commit! It helps a ton

**Pull request merged**
