### PR TITLE
Create Dockerfile

### PR DESCRIPTION
**Pull request by oxr463**
Bug: https://github.com/Humblemonk/DiceMaiden/issues/117

### CODE REVIEW

**Comment by oxr463** [comment]
I still need to account for the environment variables, and add the appropriate documentation.

**Comment by oxr463** [comment]
@Humblemonk please review.

**Comment by Humblemonk** [comment]
I will work on merging this over the holidays. Sorry been really busy with real life :)

**Comment by oxr463** [comment]
No worries!

**Pull request merged**
