### PR TITLE
Adds Botch counting

### PR DESCRIPTION
**Pull request by EvRumsey**
This mostly resolves Issue #52 .

Creates a `b` prefix in the style of simple output which returns a separate count of die results <= the number that follows.

At least one comment on Issue #52 suggests additional functionality around returning more game system specific results, but this takes care of the general case.

### CODE REVIEW

**Comment by Humblemonk** [comment]
Nice! I will work on merging this over the holidays

**Comment by ThatGuyWhatsMadeofCheese** [comment]
Once this is merged and I have a chance to make sure it works how I'm thinking, I'll probably make a PR to update the Sunsails alias to include b1. So thanks EvRumsey, for doing the general case. The mechanic in Sunsails is so unlikely to matter that it didn't seem worth coding to check, when it could be done manually, but this'll be quite convenient.

**Comment by ThatGuyWhatsMadeofCheese** [comment]
While we're on the subject, in my case, what I'll want to be checking is if half or more of the dice rolled in total are 1s, which is made more complicated by the fact that the roll will also explode indefinitely.

I'm considering writing a botch ratio tag, br, that would do botch, but display it as botch_counter/total dice rolled. But I don't know if this would ever be useful to anybody else, or if it'd be too niche to include. (We could always just count all the explosions and just add the original number of rolls, so it's not even that essential for our group, except that it would let us use the simple tag.)

Thoughts?

**Comment by EvRumsey** [comment]
Botch ratio would be useful for my use case (Shadowrun 4e) as well. I think we could fudge a similar total dice count and take a ratio, but I think that'd be some regex black magic that would break later.

**Comment by ThatGuyWhatsMadeofCheese** [comment]
I was thinking more along the lines of adding something into the explode function that incremented the counter every time it exploded, and that counter just only gets displayed if br is active.

**Comment by ThatGuyWhatsMadeofCheese** [comment]
Ok, so if I define a global variable that starts equal to the number of dice initially rolled, and add an incrementor to that variable in the explode loop, we would have that total available to use for this, and anything else that we want it for down the road.

@Humblemonk, my question to you is, what would you want that variable to be called, (so I don't name it something too close to some other variable that already exists,)?

**Comment by Humblemonk** [comment]
Finally closing this out in a separate commit. Had to rewrite it a bit to support slash commands and add functionality to dice bag gem. Also ran into a few bugs with the original code. Happy to have some form of botch support finally :)

**Pull request closed without merging**
